# SPRING PROPERTIES
spring:
  # JPA PROPERTIES
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties.org.hibernate.envers:
      audit_table_suffix: _audit
      revision_field_name: revision_id
      revision_type_field_name: revision_operation
      store_data_at_delete: true
      # track_entities_changed_in_revision: true
      # audit_strategy: org.hibernate.response.strategy.ValidityAuditStrategy
  # DATASOURCE PROPERTIES
  datasource:
    driver-class-name: ${US_DB_DRIVER:org.postgresql.Driver}
    hikari.maximum-pool-size: ${US_DB_POOL:5}
  # LIQUIBASE PROPERTIES
  liquibase:
    change-log: classpath:/liquibase/db.changelog.xml