version: '4.14.0'

services:
  postgres:
    image: postgres
    container_name: postgres-compose
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./imageConfiguration/postgres/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  keycloak:
    depends_on:
      - postgres
    image: jboss/keycloak:16.1.1
    container_name: keycloak-compose
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      KEYCLOAK_IMPORT: ./imageConfiguration/keycloak/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: postgres
      DB_ADDR: ${KEYCLOACK_DB_ADDRESS:-postgres}
      DB_DATABASE: ${KEYCLOACK_DB_NAME:-keycloack_db}
      DB_SCHEMA: ${KEYCLOACK_DB_SCHEMA:-public}
      DB_USER: ${KEYCLOACK_DB_USER:-evoice_keycloack_db}
      DB_PASSWORD: ${KEYCLOACK_DB_USER:-evoice_keycloack_db}
      KEYCLOAK_USER: ${KEYCLOACK_DB_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOACK_DB_USER:-admin}