version: '4.14.0'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-compose
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configuration/postgres/script:/docker-entrypoint-initdb.d/
    environment:
      # Default account
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-compose
    command:
      - start-dev
      - --http-relative-path=/auth
      - --import-realm
    volumes:
      - ./configuration/keycloak:/opt/keycloak/data/import
    environment:
      # Default account
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
      # Custom database for keycloak
      KC_DB: ${KEYCLOAK_DB:-postgres}
      KC_DB_URL_HOST: ${KEYCLOAK_DB:-postgres}
      KC_DB_URL_PORT: ${KEYCLOAK_DB_PORT:-5432}
      KC_DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA:-public}
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME:-keycloak_db}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-evoice_keycloak_db}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-evoice_keycloak_db}
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080

  zipkin:
    depends_on:
      - postgres
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - ${ZIPKIN_PORT:-9411}:9411

volumes:
  postgres_data:
    driver: local