global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'evoice-api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'evoice-api-gateway:8091' ]
        labels:
          application: 'Api Gateway Service Application'
    basic_auth:
      username: 'admin'
      password: 'admin'
  - job_name: 'evoice-user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'evoice-user-service:8092' ]
        labels:
          application: 'User Service Application'