# SPRING PROPERTIES
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application.name: evoice-api-gateway
  security.oauth2.resourceserver.jwt.issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/auth/realms/evoice-realm-service}
  cloud:
    gateway:
      routes:
        ## OPEN API Route
        - id: open-api
          uri: ${SERVICE_URL:http://localhost:${server.port}}
          predicates:
            - Path=/api-docs/**
          filters:
            - RewritePath=/api-docs/evoice-(?<path>.*), /services/$\{path}/api-docs
        ## User Service Route
        - id: evoice-user-service
          uri: lb://evoice-user-service
          predicates:
            - Path=/services/user-service/**
          filters:
            ### Note: order matters!
            - RewritePath=/services/user-service/api/(?<segment>.*), /v1/api/$\{segment}
            - RewritePath=/services/user-service/(?<segment>.*), /$\{segment}

# OPEN API PROPERTIES
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    groups.enabled: true
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: evoice-user-service/
      pathsToMatch:
        - /services/user-service/**

# EUREKA PROPERTIES
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8090/eureka}
    register-with-eureka: false
  instance:
    prefer-ip-address: true

# LOGGING PROPERTIES
logging:
  level:
    root: debug
    org.springframework.cloud:
      gateway: debug
      gateway.route.RouteDefinitionRouteLocator: debug

# METRICS PROPERTIES
management:
  ## ACTUATOR / PROMETHEUS PROPERTIES
  endpoints:
    web.exposure.include: health, info, prometheus, gateway
  endpoint.gateway.enabled: true
  tracing.sampling.probability: 1.0
  metrics.tags:
    application: ${spring.application.name}
  ## ZIPKIN PROPERTIES
  zipkin.tracing.endpoint: ${ZIPKIN_URL:http://localhost::9411/api/v2/spans}


# THIS SERVICE OTHER PROPERTIES
server.port: ${EVOICE_API_GATEWAY_PORT:8091}