# SPRING PROPERTIES
spring:
  application.name: evoice-api-gateway
  security.oauth2.resourceserver.jwt.issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth/realms/evoice-realm
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        # Naming Service Route
        - id: evoice-naming-service
          uri: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8090}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Naming Service Static Resources Route
        - id: evoice-naming-service-static
          uri: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8090}
          predicates:
            - Path=/eureka/**
        # User Service Route
        - id: evoice-user-service
          uri: lb://evoice-user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - RewritePath=/api/user-service(?<segment>/?.*), $\{segment}

# EUREKA PROPERTIES
eureka:
  client.serviceUrl:
    defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8090}/eureka
  instance.hostname: ${EUREKA_HOST:localhost}

# LOGGING PROPERTIES
logging:
  level:
    root: debug
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: debug
    org.springframework.cloud.gateway: debug

# ACTUATOR PROPERTIES
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

# THIS SERVICE OTHER PROPERTIES
server.port: 8091