# SPRING PROPERTIES
spring:
  application.name: evoice-api-gateway
  security.oauth2.resourceserver.jwt.issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/auth/realms/evoice-realm-service}
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        # Naming Service Route
        - id: evoice-naming-service
          uri: ${EUREKA_URL:http://localhost:8090/eureka}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Naming Service Static Resources Route
        - id: evoice-naming-service-static
          uri: ${EUREKA_URL:http://localhost:8090/eureka}
          predicates:
            - Path=/eureka/**
        # User Service Route
        - id: evoice-user-service
          uri: lb://evoice-user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - RewritePath=/api/user-service(?<segment>/?.*), $\{segment}

# EUREKA PROPERTIES
eureka:
  client.serviceUrl:
    defaultZone: ${EUREKA_URL:http://localhost:8090/eureka}
  instance:
    prefer-ip-address: true

# LOGGING PROPERTIES
logging:
  level:
    root: debug
    org.springframework.cloud:
      gateway: debug
      gateway.route.RouteDefinitionRouteLocator: debug

# ACTUATOR PROPERTIES
management:
  endpoints:
    web.exposure.include: health, info, prometheus, gateway
  endpoint.gateway.enabled: true
  tracing.sampling.probability: 1.0
  zipkin.tracing.endpoint: ${ZIPKIN_URL:http://localhost::9411/api/v2/spans}
  metrics.tags:
    application: ${spring.application.name}

# THIS SERVICE OTHER PROPERTIES
server.port: ${EVOICE_API_GATEWAY_PORT:8091}