# SPRING PROPERTIES
spring.application.name: evoice-naming-service

# EUREKA PROPERTIES
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8090/eureka}
    register-with-eureka: false
    fetch-registry: false

# LOGGING PROPERTIES
logging.level:
  root: debug

# THIS SERVICE OTHER PROPERTIES
server.port: ${EVOICE_NAMING_SERVICE_PORT:8090}