# SPRING PROPERTIES
spring:
  application.name: evoice-user-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties.org.hibernate.envers:
      audit_table_suffix: _audit
      revision_field_name: revision_id
      revision_type_field_name: revision_operation
      store_data_at_delete: true
      # track_entities_changed_in_revision: true
      # audit_strategy: org.hibernate.response.strategy.ValidityAuditStrategy
  datasource:
    driver-class-name: ${US_DB_DRIVER:org.postgresql.Driver}
    url: ${US_DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${US_DB_USERNAME:evoice_user_db}
    password: ${US_DB_PASSWORD:evoice_user_db}
    hikari.maximum-pool-size: ${US_DB_POOL:5}
  liquibase.change-log: classpath:/liquibase/db.changelog.xml

# EUREKA PROPERTIES
eureka:
  client.serviceUrl:
    defaultZone: ${EUREKA_URL:http://localhost:8090/eureka}
  instance.preferIpAddress: true

# LOGGING PROPERTIES
logging.level:
  root: debug

# METRICS PROPERTIES
management:
  # ACTUATOR / PROMETHEUS PROPERTIES
  endpoints:
    web.exposure.include: health, info, prometheus, gateway
  tracing.sampling.probability: 1.0
  metrics.tags:
    application: ${spring.application.name}
  # ZIPKIN PROPERTIES
  zipkin.tracing.endpoint: ${ZIPKIN_URL:http://localhost::9411/api/v2/spans}

# THIS SERVICE OTHER PROPERTIES
server.port: ${EVOICE_USER_SERVICE_PORT:8092}
