# SPRING PROPERTIES
spring:
  application:
    name: evoice-user-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_operation
            store_data_at_delete: true
            # track_entities_changed_in_revision: true
            # audit_strategy: org.hibernate.response.strategy.ValidityAuditStrategy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${US_DB_URL:jdbc:postgresql://localhost:${US_DB_PORT:5432}/${US_DB_NAME:user_db}}
    username: ${US_DB_USERNAME:evoice_user_db}
    password: ${US_DB_PASSWORD:evoice_user_db}
    hikari:
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:/liquibase/db.changelog.xml

# EUREKA PROPERTIES
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

# THIS SERVICE OTHER PROPERTIES
server:
  port: 8083
